carSearchSite/urls.py
from django.urls import path
from carSearchSite import views

app_name = "carSearch"
urlpatterns = [
    path("",views.CarSearchModel.as_view(),name="FP"),
    path('list/',views.carList,name='carList'),
    path('delInfo/<int:deleteqs>/<int:deleteimg>',views.deleteInfo,name='delInfo')
]

main/urls.py
from django.urls import path
from main import views

app_name = "main"

urlpatterns = [
    path("",views.main,name="mainpage")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("carSearch/",include("carSearchSite.urls")),
    path("deep/",include("deepLearning.urls")),
    path("machine/",include("machineLearning.urls"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carSearchSite/models.py
from django.db import models

from mysite.models import CreationModificationDateBase
from django.utils.translation import gettext_lazy as _

import os

# Create your models here.


#딥 러닝 모델
class InferencedImage(CreationModificationDateBase):
    orig_image = models.ForeignKey(
        "ImageModel",
        on_delete=models.CASCADE,
        related_name="detectedimages",
        help_text="Main Image",
        null=True,
        blank=True
    )

    inf_image_path = models.CharField(max_length=250,
                                      null=True,
                                      blank=True
                                      )
    
    detection_info = models.JSONField(null=True, blank=True)

    YOLOMODEL_CHOICES = [
        ('best.pt', 'best.pt'),
        ('last.pt', 'last.pt'),
    ]

    yolo_model = models.CharField(_('YOLOV5 Models'),
                                  max_length=250,
                                  null=True,
                                  blank=True,
                                  choices=YOLOMODEL_CHOICES,
                                  default=YOLOMODEL_CHOICES[0],
                                  help_text="Selected yolo model will download. \
                                 Requires an active internet connection."
                                  )

    model_conf = models.DecimalField(_('Model confidence'),
                                     decimal_places=2,
                                     max_digits=4,
                                     null=True,
                                     blank=True)

#이미지 저장 
class ImageModel(models.Model):
    name = models.CharField(_('Image Name'), max_length=150, null=True)
    image = models.ImageField(_("image"), upload_to='images')

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

    def __str__(self) -> str:
        return str(os.path.split(self.image.path)[-1])
    
#차량 정보
class CarInfo(models.Model):
    fue_type = [
        (0,'CNG'), 
        (1,'LPG(일반인 구입)'), 
        (2,'LPG+전기'), 
        (3,'가솔린'), 
        (4,'가솔린+CNG'), 
        (5,'가솔린+LPG'), 
        (6,'가솔린+전기'), 
        (7,'디젤'), 
        (8,'수소'),
        (9,'전기')
    ]
    carName = models.CharField(null=True,default="",max_length=200,verbose_name="car")
    carCalendar = models.DateField(null=True,verbose_name="calendar")
    carYear = models.IntegerField(null=True,default=0,verbose_name='year')
    carMonth = models.IntegerField(null=True,default=0,verbose_name='month')
    carModel = models.IntegerField(null=True,default=0,verbose_name='yearlyModel')
    
    carDistance = models.IntegerField(default=0,null=True,verbose_name='distance')
    carFuel = models.IntegerField(null=True,choices=fue_type,verbose_name='fuel')
    carprice = models.IntegerField(null=False,verbose_name='price')

    def __str__(self) -> str:
        return "{}".format(self.carCalendar)

carSearchSite/forms.py
from django import forms
from carSearchSite.models import CarInfo,ImageModel

class CarInfoForm(forms.ModelForm):
    class Meta:
        model = CarInfo
        fields = ['carCalendar','carDistance','carFuel']
        widgets = {
            'carCalendar' : forms.DateInput(
                format=('%Y/%m/%/d'),
                attrs={'class': "form-control",
                       'placeholder':'날짜를 입력해주세요',
                       'type':'date',
                       'style': 'max-width: 300px;'
                       }
                ),
            
            'carDistance' : forms.NumberInput(
                attrs={'class': "form-control",
                       'style': 'max-width: 300px;'
                      }
            ),
            
            'carFuel' : forms.Select(
                attrs={'style': 'max-width: 300px; text-align: center',
                       'class': "form-control"
                      }
            )
        }
class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ['image']

carSearchSite/views.py
import collections
from django.shortcuts import render ,redirect, reverse
from django.views.generic import View

from carSearchSite.models import CarInfo,ImageModel,InferencedImage
from carSearchSite.forms import CarInfoForm, ImageUploadForm

from django.conf import settings
from django.contrib import messages
from django.utils.dateformat import DateFormat

import torch
import joblib 
import yolov5
from ast import literal_eval


from datetime import datetime
import os
import io
from PIL import Image as I

# Create your views here.
class CarSearchModel(View):
    def get(self,request):
        form = CarInfoForm()
        imageform = ImageUploadForm()
        
        context = {
            'form':form,
            'imageform':imageform
        }
        return render(request,"carSearchSite/model1.html",context)

    def post(self,request):     
           
        # 날짜데이터 (문자열 --> 날짜)
        cy = request.POST['carCalendar']
        cy_format = "%Y-%m-%d"
        cy_year = datetime.strptime(cy,cy_format)

        #연월만 추출
        year = int(DateFormat( cy_year).format("Y")) - 2000
        month = int(DateFormat( cy_year).format("m"))
        
        # 차를 사용한 개월 
        car_year = 300 - (year*12) - month
        
        #데이터베이스 저장
        carinfo = CarInfo()
        carinfo.carCalendar = request.POST['carCalendar'] # 차량 연식
        carinfo.carDistance = request.POST['carDistance'] # 차량 주행거리
        carinfo.carFuel = request.POST['carFuel'] # 차량 연료
       
        carinfo.carYear = year
        carinfo.carMonth = month
        carinfo.carModel = car_year
       
        # 딥러닝 모델
        img = request.FILES.get('image')
        img_instance = ImageModel(
            image=img
        )
        img_instance.save()

        uploaded_img_qs = ImageModel.objects.filter().last()
        img_bytes = uploaded_img_qs.image.read()
        img = I.open(io.BytesIO(img_bytes))
        uploaded_img_qs.image.close()
        
        path_hubconfig = "yolov5"
        path_weightfile = "yolov5\\weights\\best.pt"  # or any custom trained model
        model = yolov5.load(path_weightfile)

        model.conf = settings.MODEL_CONFIDENCE
        yolo_model_name = self.request.POST.get("yolo_model")
        # classnames = model.names  #(display classes in the model)

        results = model(img, size=416)
        results_list = results.pandas().xyxy[0].to_json(orient="records")
        results_list = literal_eval(results_list)
        
        classes_name_list = [item["name"] for item in results_list]
        # class_num_list = [item["class"] for item in results_list]
        # results_counter = collections.Counter(class_num_list)
        
        
        if results_list == []:
            messages.warning(
            request, f'Model unable to predict. Try with another model.')
        else:
            results.render()
            media_folder = settings.MEDIA_ROOT
            inferenced_img_dir = os.path.join(
                    media_folder, "inferenced_image")
            if not os.path.exists(inferenced_img_dir):
                os.makedirs(inferenced_img_dir)
                    
            # Create/update the inferencedImage instance
            inf_img_qs,created = InferencedImage.objects.get_or_create(
                    orig_image=uploaded_img_qs,
                    inf_image_path=f"{settings.MEDIA_URL}inferenced_image/{uploaded_img_qs}",
                )
            inf_img_qs.detection_info = results_list
            inf_img_qs.model_conf = model.conf

            inf_img_qs.yolo_model = yolo_model_name
            inf_img_qs.save()
        torch.cuda.empty_cache()
            
        # results = model(img, size=416)
        results.render()
        results.print()
        results.pandas().xyxy[0]
        results.save()
        for img in results.ims:
            img_base64 = I.fromarray(img)
            img_base64.save(f"{inferenced_img_dir}/{uploaded_img_qs}", format="PNG")
            
        inference_img = f"{settings.MEDIA_URL}inferenced_image/{uploaded_img_qs}"
   
        carinfo.carName = classes_name_list
    
        #머신러닝 모델 가져오기
        car_learn = joblib.load('pkl\saved_model.pkl')
        car = car_learn.predict([[car_year,request.POST['carDistance'],request.POST['carFuel'],results_list[0]['class']]])
        carinfo.carprice = car # 차량 중고가
        carinfo.save()
        
        return redirect(reverse('carSearch:carList'))

def carList(request):
    form = CarInfo.objects.filter().last()
    uploaded_img_qs = ImageModel.objects.filter().last()
    inference_img = f"{settings.MEDIA_URL}inferenced_image/{uploaded_img_qs}"
    
    context = {
        "file":form,
        "image":uploaded_img_qs,
        "inf_image":inference_img
    }
    return render(request,'carSearchSite/carlist.html',context)

def deleteInfo(request,deleteqs,deleteimg):
    image = ImageModel.objects.get(id=deleteimg)
    qs = CarInfo.objects.get(id=deleteqs)
    
    media_root = settings.MEDIA_ROOT
    print('media_root:%s' % media_root)

    
    deleteimage = f"{media_root}\images\{image}"
    deleteInferenced = f"{media_root}\inferenced_image\{image}"
    
    print('deleteimage:%s' % deleteimage)
    print('deleteInferenced:%s' % deleteInferenced)
         
    #실제 파일 삭제를 위한 코드
    if os.path.isfile(deleteimage):
        os.remove(deleteimage) #실제 파일 삭제
       
    if os.path.isfile(deleteInferenced):
        os.remove(deleteInferenced) #실제 파일 삭제
         
    #DB에서 해당 정보 삭제  
    qs.delete()
    image.delete()
    
    return redirect(reverse("carSearch:FP"))
    

templates/carSearchSite/carlist.html
<!DOCTYPE html>
{% extends 'main/mainpage.html' %}
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block Masthead%}
        <!-- Masthead-->
        <header class="masthead-example" style = "background-image: url('{% static 'carSearchSite/assets/img/bg-masthead.jpg' %}'); no-repeat center center;">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white" >
                            <table class="table table-info table-striped" bordercolor="#006F84" width ="1100px" height="500px" style="white-space: nowrap;">
                                    <tr>
                                        <th>사진</th> 
                                        <th>칼럼</th>
                                        <th>속성</th>
                                   </tr>
                                    
                                    <tr>
                                        <td rowspan="6" style=><img src="{{inf_image}}" style = "height:300px; width: 200px text-align: center"  alt=""></td>
                                    </tr>
                                    <tr>
                                        <td>이름</td>
                                        <td>{{file.carName}}</td>
                                    </tr>
                                   
                                    <tr>
                                        <td>연식</td>
                                        <td>{{file.carYear}}년/{{file.carMonth}}식</td>
                                    </tr>
                                   
                                    <tr>
                                        <td>주행거리</td>
                                        <td>{{file.carDistance}} Km</td>
                                    </tr>

                                    <tr>
                                        <td>연료</td>
                                        <td>{{file.get_carFuel_display}}</td>
                                    </tr>

                                    <tr>
                                        <td>중고가 </td>
                                        <td>{{file.carprice}} 만원 </td>
                                    </tr>
                            </table>
                            <br>
                            <br>
                            <a href="{% url 'carSearch:delInfo' file.id image.id  %}"><button class='btn btn-primary'>delete</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    {% endblock  %}

    {% block IconsGrid %}{% endblock  %}
    {% block ImageShowcases %}{% endblock  %}
</html>

templates/carSearchSite/model1.html
<!DOCTYPE html>
{% extends 'main/mainpage.html' %}
<html lang="en">
<head>
    {% load static %}
    {% load bootstrap4 %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block Masthead%}
        <!-- Masthead-->
        <header class="masthead-example" style = "background-image: url('{% static 'carSearchSite/assets/img/bg-masthead.jpg' %}'); no-repeat center center;">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                           <form method="post" enctype="multipart/form-data" style="position: absolute;  top: -100px; right: 500px">
                                <fieldset style="border: 5px solid #006F84; width:300; height:200;  padding:20px;">
                                    <legend>차량 정보</legend>
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% bootstrap_form imageform %}
                                <br>
                                <br>
                                <input class="btn btn-primary" type="submit" value="upload">
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    {% endblock  %}

    {% block IconsGrid %}{% endblock  %}
    {% block ImageShowcases %}{% endblock  %}
    
</body>
</html>